;user variables for NEXA RS UI
;best not to change the default values!
;but if you want, then do so by all means!

[Variables]
fontname="Nexa Light"
fontnamebold="Nexa Bold"
backcolor=0,0,0,0
frontcolor=0,0,0,0
textcolor1=25,25,25,225
textcolor2=25,25,25,245
textcolor3=0,0,0,0
textcolor4=0,0,0,190
tsize1=35
tsizedate=55
linecolor1=0,0,0,200
linecolor2=0,0,0,180
linecolor3=0,0,0,160
linecolor4=0,0,0,120
linecolor41=0,0,0,100
linecolor42=0,0,0,80
linecolor5=255,255,255,180
linecolor6=255,255,255,160
playername=CAD